export const currencySelectOptions = [
    { label: "USD", value: "usd" },
    { label: "EUR", value: "eur" },
    { label: "GBP", value: "gbp" },
    { label: "JPY", value: "jpy" },
    { label: "AUD", value: "aud" },
    { label: "CAD", value: "cad" },
    { label: "CHF", value: "chf" },
    { label: "CNY", value: "cny" },
    { label: "INR", value: "inr" },
    { label: "MXN", value: "mxn" },
    { label: "BRL", value: "brl" },
    { label: "RUB", value: "rub" },
    { label: "ZAR", value: "zar" },
    { label: "SGD", value: "sgd" },
    { label: "KRW", value: "krw" },
];